Add JwtHeader JsonConstructor Parameterless Constructor and decorator
jwt-dotnet/jwt pull request #475
Opened 2023-07-11 22:54 UTC by andreijw

When running this project targetting dotnet 8.0 and building with AOT. If the JwtHeader class gets deserialized/serialized with the SystemTextSerializer.cs it throws an exception:

"Missing a Parameterless constructor <Class>" 

I have added the System.Text.Json.JsonConstructor decorator with a fully qualified name since the Newtonsoft.Json namespace also have that same JsonConstructor decorator.  I also wrapped this behind the MODERN_DOTNET compiler directive to conserve backwards compatibility .

2023-07-11 23:02 UTC, abatishchev requested changes

2023-07-11 23:02 UTC, abatishchev commented on src/JWT/Builder/JwtHeader.cs
> +#if MODERN_DOTNET
Please move it to the top of the class, so the ctor(s) would be before properties but after fields

2023-07-11 23:03 UTC, abatishchev commented
Thank you for the contribution! Please make additional necessary changes:

1. Bump the third element in the version inside JWT.csproj
2. Update the change log
3. Is it possible to add a unit test that would illustrate the issue? Why it doesn't fail on regular platforms?

2023-07-12 17:44 UTC, andreijw commented
@abatishchev  Ok will do! Might take a few days since I need to shift focus to some critical issues at work, but if I get the chance I will knock out these simple changes as requested. I appreciate the feedback

2023-07-12 17:49 UTC, abatishchev commented
Just did all of the above myself, but a unit test to demonstrate the issue. Please add. Thanks again for the contribution!

2023-07-17 16:46 UTC, andreijw commented
Hello @abatishchev I'm a little confused on the best way to add a unit test for this specific issue.

I only encounter this issue, when I have an application that I have compiled with AOT with some command similar to 
`dotnet publish SomeProject.csproj -c Release --runtime=linux-x64 /p:Version=VERSION` and it throws a runtime warning when the class (in this case the JWTHeader.cs) is serialized using System.Text.Json since it's missing a parameterless constructor and it's not annotated with the JsonConstructor attribute. 

Would adding a unit test that specifically invokes the parameterless constructor without any issues in both MODERN_DOTNET and non-MODERN_DOTNET platforms suffice your wants? I fear that to truly demonstrated the issue we need an integration / end-to-end test that has an AOT-compiled application and tries to serialize this class to throw a runtime error.

Please let me know your thoughts on this.

Regards

2023-07-17 17:37 UTC, abatishchev commented
> Would adding a unit test that specifically invokes the parameterless constructor without any issues in both MODERN_DOTNET and non-MODERN_DOTNET platforms suffice your wants?

Would be a good start! Something is better than nothing :)

> I fear that to truly demonstrated the issue we need an integration / end-to-end test that has an AOT-compiled application and tries to serialize this class to throw a runtime error.

I fear this too. But it's definitely more work and totally fine if won't be a part of this PR. Would be awesome if you still could do that later!

2023-07-18 01:08 UTC, abatishchev submitted a review, later dismissed

2023-07-18 01:38 UTC, abatishchev approved these changes

2023-07-18 01:39 UTC, merged

2023-07-18 16:12 UTC, andreijw commented
Hello @abatishchev

Is there anything special that we must do in order to publish the new nuget 10.0.3? I saw that you bumped the nuget version in the csrpoj file, but I still don't see the nuget released. I also checked the PR and merge build and ensured that they were both completed without any issues.

Regards,

Andrei Jaume

2023-07-18 16:17 UTC, abatishchev commented
Sorry, didn't have a chance to press the button yet. Will do it in a moment.

2023-07-18 16:22 UTC, abatishchev commented
[10.0.3](https://www.nuget.org/packages/JWT/10.0.3) should become available soon (once NuGet finishes indexing the package).